<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace BingAds\v10\CampaignManagement;


/**
     * This service operation is reserved for future use.
     * @link http://msdn.microsoft.com/en-us/library/dn277499(v=msads.100).aspx AddAdGroupCriterions Request Object
     * 
     * @uses AdGroupCriterion
     * @uses CriterionType
     * @used-by BingAdsCampaignManagementService::AddAdGroupCriterions
     */
final class AddAdGroupCriterionsRequest
{
    /**
     * The identifier of the account to add the criterions to.
     * @var integer
     */
    public $AccountId;
    /**
     * A list of ad group criterions.
     * @var AdGroupCriterion[]
     */
    public $AdGroupCriterions;
    /**
     * The type of ad group criterion to add.
     * @var CriterionType
     */
    public $CriterionType;
}
