<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace BingAds\v10\CampaignManagement;


/**
     * Associates the specified ad groups with the respective remarketing lists.
     * @link http://msdn.microsoft.com/en-us/library/mt735048(v=msads.100).aspx AddAdGroupRemarketingListAssociations Request Object
     * 
     * @uses AdGroupRemarketingListAssociation
     * @used-by BingAdsCampaignManagementService::AddAdGroupRemarketingListAssociations
     */
final class AddAdGroupRemarketingListAssociationsRequest
{
    /**
     * The list of up to 1,000 ad group remarketing list associations that you want to add.
     * @var AdGroupRemarketingListAssociation[]
     */
    public $AdGroupRemarketingListAssociations;
}
