<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace BingAds\v10\CampaignManagement;


/**
     * Associates the specified ad groups with the respective remarketing lists.
     * @link http://msdn.microsoft.com/en-us/library/mt735048(v=msads.100).aspx AddAdGroupRemarketingListAssociations Response Object
     * 
     * @uses BatchError
     * @used-by BingAdsCampaignManagementService::AddAdGroupRemarketingListAssociations
     */
final class AddAdGroupRemarketingListAssociationsResponse
{
    /**
     * A list of unique system identifiers corresponding to the ad group remarketing list associations that were added.
     * @var integer[]
     */
    public $AssociationIds;
    /**
     * An array of BatchError objects that contain details for any request items that were not successful.
     * @var BatchError[]
     */
    public $PartialErrors;
}
