<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace BingAds\v10\CampaignManagement;


/**
     * Adds one or more campaign criterions that help determine whether ads in each campaign get served.
     * @link http://msdn.microsoft.com/en-us/library/dn913127(v=msads.100).aspx AddCampaignCriterions Response Object
     * 
     * @uses BatchErrorCollection
     * @used-by BingAdsCampaignManagementService::AddCampaignCriterions
     */
final class AddCampaignCriterionsResponse
{
    /**
     * A list of unique system identifiers corresponding to the criterion that were added.
     * @var integer[]
     */
    public $CampaignCriterionIds;
    /**
     * An array of BatchErrorCollection objects that contain details for any criterion that were not successfully added.
     * @var BatchErrorCollection[]
     */
    public $NestedPartialErrors;
}
