<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace BingAds\v10\CampaignManagement;


/**
     * Adds negative keywords to the specified campaign or ad group.
     * @link http://msdn.microsoft.com/en-us/library/dn743724(v=msads.100).aspx AddNegativeKeywordsToEntities Response Object
     * 
     * @uses IdCollection
     * @uses BatchErrorCollection
     * @used-by BingAdsCampaignManagementService::AddNegativeKeywordsToEntities
     */
final class AddNegativeKeywordsToEntitiesResponse
{
    /**
     * A list of IdCollection corresponding to the negative keywords that were added for the corresponding entity.
     * @var IdCollection[]
     */
    public $NegativeKeywordIds;
    /**
     * An array of BatchErrorCollection objects that contain details for any negative keyword that were not successfully added.
     * @var BatchErrorCollection[]
     */
    public $NestedPartialErrors;
}
