<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace BingAds\v10\CampaignManagement;


/**
     * Defines the status values of an ad group remarketing list association.
     * @link http://msdn.microsoft.com/en-us/library/mt735043(v=msads.100).aspx AdGroupRemarketingListAssociationStatus Value Set
     * 
     * @used-by AdGroupRemarketingListAssociation
     */
final class AdGroupRemarketingListAssociationStatus
{
    /** The ad group remarketing list association is active. */
    const Active = 'Active';
    /** The ad group remarketing list association is paused. */
    const Paused = 'Paused';
    /** Reserved for internal use. */
    const Deleted = 'Deleted';
}
