<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace BingAds\v10\CampaignManagement;


/**
     * Represents the association between an ad group and a remarketing list.
     * @link http://msdn.microsoft.com/en-us/library/mt735042(v=msads.100).aspx AdGroupRemarketingListAssociation Data Object
     * 
     * @uses AdGroupRemarketingListAssociationStatus
     * @used-by AddAdGroupRemarketingListAssociationsRequest
     * @used-by DeleteAdGroupRemarketingListAssociationsRequest
     * @used-by GetAdGroupRemarketingListAssociationsResponse
     * @used-by UpdateAdGroupRemarketingListAssociationsRequest
     */
final class AdGroupRemarketingListAssociation
{
    /**
     * The Bing Ads identifier of the ad group associated with the remarketing list.
     * @var integer
     */
    public $AdGroupId;
    /**
     * The percentage you want to increase/decrease the bid amount for the remarketing list.
     * @var double
     */
    public $BidAdjustment;
    /**
     * The Bing Ads identifier for the association between an ad group and remarketing list.
     * @var integer
     */
    public $Id;
    /**
     * The Bing Ads identifier of the remarketing list associated with the ad group.
     * @var integer
     */
    public $RemarketingListId;
    /**
     * The association status.
     * @var AdGroupRemarketingListAssociationStatus
     */
    public $Status;
}
