<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace BingAds\v10\CampaignManagement;


/**
     * Defines an app ad extension that can be included in a text ad.
     * @link http://msdn.microsoft.com/en-us/library/dn817898(v=msads.100).aspx AppAdExtension Data Object
     * 
     * @uses AppUrl
     * @uses CustomParameters
     */
final class AppAdExtension extends AdExtension
{
    public $AppPlatform;
    public $AppStoreId;
    public $DestinationUrl;
    public $DevicePreference;
    public $DisplayText;
    public $FinalAppUrls;
    public $FinalMobileUrls;
    public $FinalUrls;
    public $TrackingUrlTemplate;
    public $UrlCustomParameters;
}
