<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace BingAds\v10\CampaignManagement;


/**
     * Defines the base object of a bidding scheme for how you want to manage your bids.
     * @link http://msdn.microsoft.com/en-us/library/mt709087(v=msads.100).aspx BiddingScheme Data Object
     * 
     * @used-by AdGroup
     * @used-by Campaign
     * @used-by Keyword
     */
class BiddingScheme
{
    public $Type;
}
