<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace BingAds\v10\CampaignManagement;


/**
     * Represents a budget that can be shared by any campaigns in an account.
     * @link http://msdn.microsoft.com/en-us/library/mt750548(v=msads.100).aspx Budget Data Object
     * 
     * @uses BudgetLimitType
     * @used-by AddBudgetsRequest
     * @used-by GetBudgetsByIdsResponse
     * @used-by UpdateBudgetsRequest
     */
final class Budget
{
    public $Amount;
    public $AssociationCount;
    public $BudgetType;
    public $Id;
    public $Name;
}
