<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace BingAds\v10\CampaignManagement;


/**
     * Defines an object that specifies additional text about your business, products, or services to include in a text ad.
     * @link http://msdn.microsoft.com/en-us/library/mt691508(v=msads.100).aspx CalloutAdExtension Data Object
     */
final class CalloutAdExtension extends AdExtension
{
    /**
     * Additional callout text about your business, products, or services to include in a text ad.
     * @var string
     */
    public $Text;
}
