<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace BingAds\v10\CampaignManagement;


/**
     * Defines a list of optional Campaign elements that you can request when calling GetCampaignsByAccountId and GetCampaignsByIds.
     * @link http://msdn.microsoft.com/en-us/library/mt709093(v=msads.100).aspx CampaignAdditionalField Value Set
     * 
     * @used-by GetCampaignsByAccountIdRequest
     * @used-by GetCampaignsByIdsRequest
     */
final class CampaignAdditionalField
{
    /** Includes the BiddingScheme element in the Campaign object. */
    const BiddingScheme = 'BiddingScheme';
    /** Includes the BudgetId element in the Campaign object. */
    const BudgetId = 'BudgetId';
}
