<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace BingAds\v10\CampaignManagement;


/**
     * This service operation is reserved for future use.
     * @link http://msdn.microsoft.com/en-us/library/dn236302(v=msads.100).aspx DeleteAdGroupCriterions Request Object
     * 
     * @uses CriterionType
     * @used-by BingAdsCampaignManagementService::DeleteAdGroupCriterions
     */
final class DeleteAdGroupCriterionsRequest
{
    /**
     * The identifier of the account that owns the criterion to delete.
     * @var integer
     */
    public $AccountId;
    /**
     * A list of unique identifiers that identify the criterion to delete.
     * @var integer[]
     */
    public $AdGroupCriterionIds;
    /**
     * The identifier of the ad group that owns the criterion to delete.
     * @var integer
     */
    public $AdGroupId;
    /**
     * The type of ad group criterion to delete.
     * @var CriterionType
     */
    public $CriterionType;
}
