<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace BingAds\v10\CampaignManagement;


/**
     * Defines an object that represents the enhanced CPC bid strategy type.
     * @link http://msdn.microsoft.com/en-us/library/mt709089(v=msads.100).aspx EnhancedCpcBiddingScheme Data Object
     */
final class EnhancedCpcBiddingScheme extends BiddingScheme
{
}
