<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace BingAds\v10\CampaignManagement;


/**
     * Defines values that you can use to determine whether the remarketing list can only be associated with ad groups within one specified account, or can be associated with any ad groups across all of the customer's accounts.
     * @link http://msdn.microsoft.com/en-us/library/mt735045(v=msads.100).aspx EntityScope Value Set
     * 
     * @used-by ConversionGoal
     * @used-by RemarketingList
     */
final class EntityScope
{
    /** The remarketing list can only be associated with ad groups within one specified account. */
    const Account = 'Account';
    /** The remarketing list can be associated with any ad groups across all of the customer's accounts. */
    const Customer = 'Customer';
}
