<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace BingAds\v10\CampaignManagement;


/**
     * Defines an expanded text ad.
     * @link http://msdn.microsoft.com/en-us/library/mt750599(v=msads.100).aspx ExpandedTextAd Data Object
     */
final class ExpandedTextAd extends Ad
{
    public $DisplayUrl;
    public $Path1;
    public $Path2;
    public $Text;
    public $TitlePart1;
    public $TitlePart2;
}
