<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace BingAds\v10\CampaignManagement;


/**
     * Gets the migration status info for the specified accounts.
     * @link http://msdn.microsoft.com/en-us/library/mt706125(v=msads.100).aspx GetAccountMigrationStatuses Request Object
     * 
     * @used-by BingAdsCampaignManagementService::GetAccountMigrationStatuses
     */
final class GetAccountMigrationStatusesRequest
{
    /**
     * The identifiers of each account to request migration status.
     * @var integer[]
     */
    public $AccountIds;
    /**
     * Filters the returned migration status by migration type.
     * @var string
     */
    public $MigrationType;
}
