<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace BingAds\v10\CampaignManagement;


/**
     * Gets the ad group remarketing list associations.
     * @link http://msdn.microsoft.com/en-us/library/mt735050(v=msads.100).aspx GetAdGroupRemarketingListAssociations Response Object
     * 
     * @uses AdGroupRemarketingListAssociation
     * @uses BatchError
     * @used-by BingAdsCampaignManagementService::GetAdGroupRemarketingListAssociations
     */
final class GetAdGroupRemarketingListAssociationsResponse
{
    /**
     * The list of ad group remarketing list associations do not correspond directly to the ad group identifiers specified in the request because there can be multiple remarketing lists associated with each ad group specified in the request.
     * @var AdGroupRemarketingListAssociation[]
     */
    public $AdGroupRemarketingListAssociations;
    /**
     * An array of BatchError objects that contain details for any request items that were not successful.
     * @var BatchError[]
     */
    public $PartialErrors;
}
