<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace BingAds\v10\CampaignManagement;


/**
     * Gets the ad group remarketing list associations.
     * @link http://msdn.microsoft.com/en-us/library/mt735050(v=msads.100).aspx GetAdGroupRemarketingListAssociations Request Object
     * 
     * @used-by BingAdsCampaignManagementService::GetAdGroupRemarketingListAssociations
     */
final class GetAdGroupRemarketingListAssociationsRequest
{
    /**
     * A list of unique ad group identifiers that identify the ad group remarketing list associations to get.
     * @var integer[]
     */
    public $AdGroupIds;
}
