<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace BingAds\v10\CampaignManagement;


/**
     * Retrieves the specified ads from the specified ad group.
     * @link http://msdn.microsoft.com/en-us/library/dn236296(v=msads.100).aspx GetAdsByIds Request Object
     * 
     * @uses AdType
     * @used-by BingAdsCampaignManagementService::GetAdsByIds
     */
final class GetAdsByIdsRequest
{
    /**
     * The identifier of the ad group that contains the ads to get.
     * @var integer
     */
    public $AdGroupId;
    /**
     * A maximum of 20 identifiers of the requested ads.
     * @var integer[]
     */
    public $AdIds;
    /**
     * One or more types of ads to return.
     * @var AdType[]
     */
    public $AdTypes;
}
