<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace BingAds\v10\CampaignManagement;


/**
     * Gets the specified criterions.
     * @link http://msdn.microsoft.com/en-us/library/dn277520(v=msads.100).aspx GetAdGroupCriterionsByIds Request Object
     * 
     * @uses CriterionType
     * @used-by BingAdsCampaignManagementService::GetAdGroupCriterionsByIds
     */
final class GetAdGroupCriterionsByIdsRequest
{
    /**
     * The identifier of the account that owns the criterions to get.
     * @var integer
     */
    public $AccountId;
    /**
     * A list of unique identifiers that identify the criterions to get.
     * @var integer[]
     */
    public $AdGroupCriterionIds;
    /**
     * The identifier of the ad group that owns the criterions to get.
     * @var integer
     */
    public $AdGroupId;
    /**
     * The types of ad group criterion to get, for example ProductPartition.
     * @var CriterionType
     */
    public $CriterionType;
}
