<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace BingAds\v10\CampaignManagement;


/**
     * Gets the list of supported sales country codes for Bing Shopping campaigns.
     * @link http://msdn.microsoft.com/en-us/library/mt750281(v=msads.100).aspx GetBSCCountries Response Object
     * 
     * @used-by BingAdsCampaignManagementService::GetBSCCountries
     */
final class GetBSCCountriesResponse
{
    /**
     * The list of supported sales country codes for Bing Shopping campaigns.
     * @var string[]
     */
    public $CountryCodes;
}
