<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace BingAds\v10\CampaignManagement;


/**
     * Gets the specified campaign criterions.
     * @link http://msdn.microsoft.com/en-us/library/dn913135(v=msads.100).aspx GetCampaignCriterionsByIds Request Object
     * 
     * @uses CampaignCriterionType
     * @used-by BingAdsCampaignManagementService::GetCampaignCriterionsByIds
     */
final class GetCampaignCriterionsByIdsRequest
{
    /**
     * A list of unique identifiers that identify the campaign criterions to get.
     * @var integer[]
     */
    public $CampaignCriterionIds;
    /**
     * The unique identifier of the campaign whose criterions you want to get.
     * @var integer
     */
    public $CampaignId;
    /**
     * The types of campaign criterion to get, for example ProductScope.
     * @var CampaignCriterionType
     */
    public $CriterionType;
}
