<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace BingAds\v10\CampaignManagement;


/**
     * Gets the remarketing lists that can be associated with entities in the specified account.
     * @link http://msdn.microsoft.com/en-us/library/mt735049(v=msads.100).aspx GetRemarketingLists Request Object
     * 
     * @used-by BingAdsCampaignManagementService::GetRemarketingLists
     */
final class GetRemarketingListsRequest
{
    /**
     * A maximum of 100 identifiers of the remarketing lists to get.
     * @var integer[]
     */
    public $RemarketingListIds;
}
