<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace BingAds\v10\CampaignManagement;


/**
     * Gets the remarketing lists that can be associated with entities in the specified account.
     * @link http://msdn.microsoft.com/en-us/library/mt735049(v=msads.100).aspx GetRemarketingLists Response Object
     * 
     * @uses RemarketingList
     * @uses BatchError
     * @used-by BingAdsCampaignManagementService::GetRemarketingLists
     */
final class GetRemarketingListsResponse
{
    /**
     * An array of RemarketingList objects that corresponds directly to the remarketing list identifiers that you specified in the request.
     * @var RemarketingList[]
     */
    public $RemarketingLists;
    /**
     * An array of BatchError objects that contain details for any request items that were not successful.
     * @var BatchError[]
     */
    public $PartialErrors;
}
