<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace BingAds\v10\CampaignManagement;


/**
     * Defines an object that represents the inherit from parent bid strategy type.
     * @link http://msdn.microsoft.com/en-us/library/mt709092(v=msads.100).aspx InheritFromParentBiddingScheme Data Object
     */
final class InheritFromParentBiddingScheme extends BiddingScheme
{
}
