<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace BingAds\v10\CampaignManagement;


/**
     * Defines an object that can contain different types of geographical targets, for example lists of city and state targets.
     * @link http://msdn.microsoft.com/en-us/library/bb671646(v=msads.100).aspx LocationTarget Data Object
     * 
     * @uses CityTarget
     * @uses CountryTarget
     * @uses IntentOption
     * @uses MetroAreaTarget
     * @uses PostalCodeTarget
     * @uses RadiusTarget
     * @uses StateTarget
     * @used-by Target
     */
final class LocationTarget
{
    public $CityTarget;
    public $CountryTarget;
    public $IntentOption;
    public $MetroAreaTarget;
    public $PostalCodeTarget;
    public $RadiusTarget;
    public $StateTarget;
}
