<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace BingAds\v10\CampaignManagement;


/**
     * Defines the base object of media.
     * @link http://msdn.microsoft.com/en-us/library/dn195580(v=msads.100).aspx Media Data Object
     * 
     * @used-by AddMediaRequest
     * @used-by GetMediaByIdsResponse
     */
class Media
{
    /**
     * The unique Bing Ads identifier of the media.
     * @var integer
     */
    public $Id;
    /**
     * The media type.
     * @var string
     */
    public $MediaType;
    /**
     * The type of media to add to the media library.
     * @var string
     */
    public $Type;
}
