<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace BingAds\v10\CampaignManagement;


/**
     * Defines the set of rules that can be used to target different groups of people with a remarketing list.
     * @link http://msdn.microsoft.com/en-us/library/mt735044(v=msads.100).aspx RemarketingListTemplate Value Set
     * 
     * @used-by RemarketingList
     */
final class RemarketingListTemplate
{
    /** Visitors of a page are added to your remarketing list. */
    const VisitorsOfAPage = 'VisitorsOfAPage';
    /** Visitors of a page who also visited another page are added to your remarketing list. */
    const VisitorsOfAPageAndAnotherPage = 'VisitorsOfAPageAndAnotherPage';
    /** Visitors of a page who did not visit another page are added to your remarketing list. */
    const VisitorsOfAPageButNotAnotherPage = 'VisitorsOfAPageButNotAnotherPage';
    /** Custom events are added to your remarketing list. */
    const CustomEvent = 'CustomEvent';
}
