<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace BingAds\v10\CampaignManagement;


/**
     * Defines the targeting setting that is applicable for all remarketing lists that are associated with a given ad group.
     * @link http://msdn.microsoft.com/en-us/library/mt735046(v=msads.100).aspx RemarketingTargetingSetting Value Set
     * 
     * @used-by AdGroup
     */
final class RemarketingTargetingSetting
{
    /** Show ads to people searching for your ad, with the option to change the bid amount for people included in the remarketing list. */
    const BidOnly = 'BidOnly';
    /** Show ads only to people included in the remarketing list, with the option to change the bid amount. */
    const TargetAndBid = 'TargetAndBid';
}
