<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace BingAds\v10\CampaignManagement;


/**
     * Associates the specified target with the specified campaign.
     * @link http://msdn.microsoft.com/en-us/library/dn277512(v=msads.100).aspx SetTargetToCampaign Request Object
     * 
     * @used-by BingAdsCampaignManagementService::SetTargetToCampaign
     */
final class SetTargetToCampaignRequest
{
    /**
     * The identifier of the campaign to associate with the target.
     * @var integer
     */
    public $CampaignId;
    /**
     * The identifier of the target to associate with the campaign.
     * @var integer
     */
    public $TargetId;
    /**
     * If the specified CampaignId is already associated with a target, this element determines whether to replace the existing association between the campaign and target with the specified TargetId.
     * @var boolean
     */
    public $ReplaceAssociation;
}
