<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace BingAds\v10\CampaignManagement;


/**
     * Defines an object with one sitelink per ad extension.
     * @link http://msdn.microsoft.com/en-us/library/mt767903(v=msads.100).aspx Sitelink2AdExtension Data Object
     * 
     * @uses AppUrl
     * @uses CustomParameters
     */
final class Sitelink2AdExtension extends AdExtension
{
    public $Description1;
    public $Description2;
    public $DestinationUrl;
    public $DevicePreference;
    public $DisplayText;
    public $FinalAppUrls;
    public $FinalMobileUrls;
    public $FinalUrls;
    public $TrackingUrlTemplate;
    public $UrlCustomParameters;
}
