<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace BingAds\v10\CampaignManagement;


/**
     * Defines the status of a website placement bid.
     * @link http://msdn.microsoft.com/en-us/library/dd797148(v=msads.100).aspx SitePlacementStatus Value Set
     * 
     * @used-by SitePlacement
     */
final class SitePlacementStatus
{
    const Active = 'Active';
    const Paused = 'Paused';
    const Deleted = 'Deleted';
    const Inactive = 'Inactive';
}
