<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace BingAds\v10\CampaignManagement;


/**
     * Defines a website placement bid.
     * @link http://msdn.microsoft.com/en-us/library/dd797248(v=msads.100).aspx SitePlacement Data Object
     * 
     * @uses Bid
     * @uses SitePlacementStatus
     * @used-by AddSitePlacementsRequest
     * @used-by GetSitePlacementsByAdGroupIdResponse
     * @used-by GetSitePlacementsByIdsResponse
     * @used-by UpdateSitePlacementsRequest
     */
final class SitePlacement
{
    public $Bid;
    public $Id;
    public $PlacementId;
    public $Status;
    public $Url;
}
