<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace BingAds\v10\CampaignManagement;


/**
     * Defines an object that pairs one header with between 3 and 10 snippet values that tell customers more about your business.
     * @link http://msdn.microsoft.com/en-us/library/mt734391(v=msads.100).aspx StructuredSnippetAdExtension Data Object
     */
final class StructuredSnippetAdExtension extends AdExtension
{
    public $Header;
    public $Values;
}
