<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace BingAds\v10\CampaignManagement;


/**
     * Defines an object that represents the target CPA bid strategy type.
     * @link http://msdn.microsoft.com/en-us/library/mt709094(v=msads.100).aspx TargetCpaBiddingScheme Data Object
     * 
     * @uses Bid
     */
final class TargetCpaBiddingScheme extends BiddingScheme
{
    public $MaxCpc;
    public $StartingBid;
    public $TargetCpa;
}
