<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace BingAds\v10\CampaignManagement;


/**
     * Updates the specified ads within a particular ad group.
     * @link http://msdn.microsoft.com/en-us/library/dn277531(v=msads.100).aspx UpdateAds Request Object
     * 
     * @uses Ad
     * @used-by BingAdsCampaignManagementService::UpdateAds
     */
final class UpdateAdsRequest
{
    /**
     * The ID of the ad group that contains the ads to update.
     * @var integer
     */
    public $AdGroupId;
    /**
     * A list of ads to update.
     * @var Ad[]
     */
    public $Ads;
}
