<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace BingAds\v10\CampaignManagement;


/**
     * Updates the properties of each specified ad group to remarketing list association.
     * @link http://msdn.microsoft.com/en-us/library/mt735052(v=msads.100).aspx UpdateAdGroupRemarketingListAssociations Request Object
     * 
     * @uses AdGroupRemarketingListAssociation
     * @used-by BingAdsCampaignManagementService::UpdateAdGroupRemarketingListAssociations
     */
final class UpdateAdGroupRemarketingListAssociationsRequest
{
    /**
     * The list of up to 1,000 ad group remarketing list associations to update.
     * @var AdGroupRemarketingListAssociation[]
     */
    public $AdGroupRemarketingListAssociations;
}
