<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace BingAds\v10\AdInsight;


/**
     * Defines an object that contains the suggested bid with estimated clicks and impressions opportunities.
     * @link http://msdn.microsoft.com/en-us/library/mt219336(v=msads.100).aspx BidOpportunity Data Object
     *
     * @used-by GetBidOpportunitiesResponse
     */
final class BidOpportunity extends Opportunity
{
    public $AdGroupId;
    public $CampaignId;
    public $CurrentBid;
    public $EstimatedIncreaseInClicks;
    public $EstimatedIncreaseInCost;
    public $EstimatedIncreaseInImpressions;
    public $KeywordId;
    public $MatchType;
    public $SuggestedBid;
}
