<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace BingAds\v10\AdInsight;


/**
     * Defines an object that contains the suggested budget with estimated clicks and impressions opportunities.
     * @link http://msdn.microsoft.com/en-us/library/mt219334(v=msads.100).aspx BudgetOpportunity Data Object
     *
     * @uses BudgetPoint
     * @uses BudgetLimitType
     * @used-by GetBudgetOpportunitiesResponse
     */
final class BudgetOpportunity extends Opportunity
{
    public $BudgetPoints;
    public $BudgetType;
    public $CampaignId;
    public $CurrentBudget;
    public $IncreaseInClicks;
    public $IncreaseInImpressions;
    public $PercentageIncreaseInClicks;
    public $PercentageIncreaseInImpressions;
    public $RecommendedBudget;
}
