<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace BingAds\v10\AdInsight;


/**
     * Given a list of existing keywords, this operation returns for each a list of suggested bids and estimated performance statistics.
     * @link http://msdn.microsoft.com/en-us/library/mt219285(v=msads.100).aspx GetBidLandscapeByKeywordIds Request Object
     *
     * @used-by BingAdsAdInsightService::GetBidLandscapeByKeywordIds
     */
final class GetBidLandscapeByKeywordIdsRequest
{
    /**
     * An array of identifiers of the keywords for which you want to get the list of suggested bid values with estimated performance statistics.
     * @var integer[]
     */
    public $KeywordIds;
    /**
     * When set to false, the suggested bid values might not include the keyword's current bid.
     * @var boolean
     */
    public $IncludeCurrentBid;
}
