<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace BingAds\v10\AdInsight;


/**
     * Gets the keyword bid opportunities of the specified ad group.
     * @link http://msdn.microsoft.com/en-us/library/mt219287(v=msads.100).aspx GetBidOpportunities Request Object
     *
     * @uses BidOpportunityType
     * @used-by BingAdsAdInsightService::GetBidOpportunities
     */
final class GetBidOpportunitiesRequest
{
    /**
     * The identifier of the ad group for which you want to determine keyword bid opportunities.
     * @var integer
     */
    public $AdGroupId;
    /**
     * The identifier of the campaign that owns the ad group specified in the AdGroupId element.
     * @var integer
     */
    public $CampaignId;
    /**
     * Determines the type or types of bid opportunities corresponding to your ad position goals.
     * @var BidOpportunityType
     */
    public $OpportunityType;
}
